### ISSUE TITLE
Typo in 1440p txt

### ISSUE THREAD

**Issue by morfeus77** [meauxdal/MiSTer_Custom_Aspect_Ratios#1]
;custom_aspect ratio_2=8:7       ; 512:224 @ 10.74, 3:6 PAR, Secret of Mana
 should be
;custom_aspect_ratio_2=8:7       ; 512:224 @ 10.74, 3:6 PAR, Secret of Mana

**Comment by meauxdal** [comment]
Fixed in commit 4d3c3b7
