### ISSUE TITLE
[Request] Add 1120p custom aspect ratios

### ISSUE THREAD

**Issue by frdarko** [meauxdal/MiSTer_Custom_Aspect_Ratios#2]
1120p (1920x1120) is 6x/5x integer on Genesis/MegaCD/NeoGeo, 5x vertical integer on NES/SNES and 5x integer on most arcade cores like CPS.

1120p modelines from atrac17:
https://twitter.com/_atrac17/status/1353564330223140864
https://twitter.com/_atrac17/status/1355263670159351811
https://www.patreon.com/posts/cps1-core-5-6x-47007108

Thank you so much for your custom aspect ratios modes!

**Comment by meauxdal** [comment]
You should be able to use a mix of the 1080p and 1200p custom ratios at 1120, as the ratio only changes when another full integer vertical multiplier occurs at vscale_mode=1. Unfortunately, it's not easy to see at a glance which ratio you need for 1120p, as the scaled resolution is generally not commented. It is accessible from the comments in most cases, however: take the base resolution of a ratio (will be something like e.g. 256:224 for NES) from 1200p.txt and multiply the width by the numerator  of the commented pixel aspect ratio (PAR) and the height by the PAR denominator - this will give you the scaled resolution. If the 1200p ratio's scaled resolution exceeds 1120 in height, use the 1080p ratio instead. 

I will see if I can get morf77 to potentially update the online calculator to give the ratios for a given custom resolution when calculating. If you end up testing out ratios in the interim, be sure to report back to let us know which ones are confirmed working at 1120p and we can spin up a new file for them.

**Comment by meauxdal** [comment]
![image](https://user-images.githubusercontent.com/68095521/107660459-4d039600-6c56-11eb-95dc-619a1d751aca.png)

We have a stopgap solution for this thanks to morf77. Plug the relevant values from the comments into the calculator and enter your custom vertical (1120 in this case). 

https://morf77.pythonanywhere.com/ar

**Comment by meauxdal** [comment]
![image](https://user-images.githubusercontent.com/68095521/107681606-416f9980-6c6d-11eb-904b-6c73a7b3578f.png)

More great work by morf77. The output now gives you a working custom_aspect_ratio which makes things less confusing. You can tell at a glance whether or not the given 1080p and 1200p ratios will fit in your vertical (and horizontal) resolution even without setting a custom vertical resolution!

**Comment by frdarko** [comment]
Thanks for the quick reply and interest and thanks to morf77's work as well. I'll try the morf77 calculator and give you feedback.

**Comment by frdarko** [comment]
You are correct, most aspect ratios are the same as 1200p or 1080p, NES and SNES have some differences. I created a PR only with cores I've tested.

**Comment by meauxdal** [comment]
I've merged your pull request. If you find more working ratios for that resolution, feel free to submit more PRs, I will be happy to merge them. Thank you!

**Comment by meauxdal** [comment]
1120p.txt has been integrated
