### ISSUE TITLE
Minimig suggestion

### ISSUE THREAD

**Issue by dfilskov** [meauxdal/MiSTer_Custom_Aspect_Ratios#4]
This seems to work for the 'Workbench' resolution in 1920x1080 with core set to PAL and Blank

[MINIMIG] ; PAL Blank 713 x 576
vscale_border=0
custom_aspect_ratio_1=713:576

and set to PAL and Blank+

[MINIMIG] ;  PAL Blank+ 640 x 572
vscale_border=254           ; requires vscale_mode=0
custom_aspect_ratio_1=640:572
custom_aspect_ratio_2=1280:572

Please test

**Comment by meauxdal** [comment]
This is very interesting, using the vscale_border to get a larger vertical resolution. I will give these settings a try and report back.

**Comment by dfilskov** [comment]
Great - please note that vscale_mode needs to be 0 to for vscale_border to work. Otherwise it's disabled - no borders to shrink the image - for some reason.

**Comment by meauxdal** [comment]
OK, the top ratio works, and is actually the first time I've successfully seen horizontal integer scaling working on Amiga. Great work. 

The second ratio with the vscale_border set does not work for me. It close, but I can see pixel shifting when I toggle the scale filter on and off with Misc/Horz Interpolation Only/Gaussian_Sharp_NN_07.txt.

At any rate, having a ratio that works at 713 x 576 is a big improvement over apparently none of them working at all. I'll try and get that one added to the repository when I push another commit.

**Comment by dfilskov** [comment]
Thanks! Did you set vscale_mode=0 in the top of the MiSTer.ini ? - and change Blank to Blank+ ?

**Comment by meauxdal** [comment]
Here are the relevant .ini sections for the two tests I did:

[Minimig] 
;PAL Blank+ 640 x 572
vscale_mode=0
vscale_border=254 ; requires vscale_mode=0
custom_aspect_ratio_1=640:572
custom_aspect_ratio_2=1280:572

^ This one was very close to integer horizontally, but I could see a few pixels shifting when toggling the filter. I had it set to Blank+ for this, but Blank was also not integer scaled horizontally (as expected). Tested on the PAL Workbench "insert disk" splash.

[Minimig] 
;PAL Blank 713 x 576
vscale_border=0
custom_aspect_ratio_1=713:576

^ This worked immediately, with video area set to Blank. Again tested on the PAL Workbench "insert disk" splash.

**Comment by dfilskov** [comment]
Got it! - I'm pretty sure that for some reason vscale_mode=0 won't work if it's not in the upper general section of the MiSTer.ini - at least not if you have a vscale_mode=1 (which I initially did) to have integer generally - that overrides the core sections, I think. Please check.

**Comment by meauxdal** [comment]
I scrolled up expecting to see vscale_mode=1 set in my 1080p alt_1.ini but it turns out I already had it set to 0 apparently. Probably due to testing the 5x crop builds which also require it. I'll try again but it looks like that was already the case. Maybe removing it from the [corename] header makes a difference for some reason.

Edit: no dice, still a slight shift when toggling the filter after removing vscale_mode=0 from the [Minimig] section but leaving it set in the top part...

**Comment by dfilskov** [comment]
Thanks for trying! - I'll test it right away - must be my mistake then - sorry!

**Comment by dfilskov** [comment]
... unless what you see is half a pixel shift ... if the Minimig - as it says in the video-info - runs double width reso (unlike any other core) internally it might be integer when not scaled and then shift all pixels one half pixel sideways when scaled. At least I think I saw something like that when testing / searching for the perfect integer settings.

**Comment by meauxdal** [comment]
I am curious what you see on your end when you try it, maybe you are able to identify this behavior when toggling the filter as specified above. If this toggling method doesn't work for Minimig, I might expect to see the same result with the other ratio here (713:576), would I not? But that one does seem to work the way ones in other cores do.

**Comment by meauxdal** [comment]
I am definitely suspecting that there are elements of the Amiga core that don't work the same way other cores do, if nothing else

**Comment by dfilskov** [comment]
Did you test the 1280x572? - the OSD blocks out the entire image on my setup so it hard to show but I see no shift when testing the double-width 1280x572. Check this out:

https://www.dropbox.com/s/hkbzxmirokfbecn/2021-02-13%2023.28.38.mp4?dl=0

**Comment by meauxdal** [comment]
Very helpful video. The resolution of the "insert disk" splash is not the same as the actual Workbench desktop for whatever reason. These ratios appear to work as intended at the actual "desktop" of Workbench. No shimmer whatsoever!

**Comment by dfilskov** [comment]
Glad we found out. I did manage to move the Workbench window title below the OSD and test the 640x572 Blank+ again - I get very little shifting (shimmering I think is when scrolling graphics slide over pixels of varying sizes - not integer - making the graphics change sizes / "waving" like a flag).

Here's what I saw - quite small image, though.
https://www.dropbox.com/s/bm60mz3ovkets5w/2021-02-13%2023.36.42.mp4?dl=0

**Comment by meauxdal** [comment]
Could you explain how you were able to determine these values? I'd like to create additional ratios for other resolutions and NTSC modes but I'm still unclear on a methodology that can be used to achieve these ratios.

**Comment by meauxdal** [comment]
Also, was the use of vscale_border the only way you were able to achieve full-integer scaling on Blank+? I ask because the use of .ini modifiers only for specific ratios is going to dramatically increase the complexity and reduce the readability of these .txt files. I'm already encountering difficulty organizing the Amiga ratio section in a useful way, and having required arguments for some but not all of the ratios increases the confusion a bit more on top of that.

I remain remarkably confused about exactly how the Minimig core and the ASCAL scaler interact. My normal ratio-finding method works in almost every case I've observed thus far, including the Atari ST core which similarly uses superwide resolutions in multiples, which I would expect not to be the case if that were the only factor.

**Comment by dfilskov** [comment]
Well - I did have to experiment with the Minimig core since - like Sorgelig write on Facebook - it sometimes displays the wrong video-info. My method is to look at the video-info the multiply the length width until they match my HDMI resolution and then caclulate the vscale_border to shink the HDMI resolution down to match the largest 1:1 ratio and them set the ratio to the largest integer resolution possible.

Anyway you're sort of lucky since I've ben working on a calculation with a friend to get the appropriate mister.ini sections for any monitor and it needs testing. Perhaps you'd be willing to try it and let us know of any issues?

You can only edit the **My HDMI width** and height - there's a tab at the bottom showing all core sections.

https://docs.google.com/spreadsheets/d/1FCpFkZg-RqLCgLSsbwkJWGZXiNkgMIWwU4pwxJdFRzk/edit

**Comment by meauxdal** [comment]
This is very interesting... It seems this sheet will achieve similar results to the ratios I have in this repository via a slightly different method.

A few notes:
- MiSTer's NES core only outputs 256x240 when in PAL/Dendy mode. In NTSC mode it will output 256x224.
- MiSTer's Genesis/MegaCD cores should be putting out the same resolutions in both NTSC and PAL modes - both television formats are capable of both 256 and 320 width modes, but in the MiSTer cores the visible lines should be the same in my experience.
- The relevant width for SMS is 256, not 248. In older builds, the core would output 248 width modes by default when the system masked the leftmost 8 columns, most commonly during horizontal scrolling - removing those columns from the visible area entirely in those modes. In the latest builds, default settings will give 256 width consistently and simply mask the leftmost 8 columns. Note: you can still achieve 248 base width during these column-masked segments of games if you use the legacy option BG: Cut, but I'm not sure why you would ever really want to do this.

I will test some of these and see if there is any functional difference between your method using vscale_borders and my repo's overall use of vscale_mode=1 - it seems if the result of your spreadsheet's calculations are integer scaled on both axes, then either method will achieve the same result.

**Comment by meauxdal** [comment]
This is a nice spreadsheet. Based on a little testing, the results are basically identical to those achieved with https://morf77.pythonanywhere.com/ar or with the existing ratios in this repository, with a few exceptions noted above. Where I remain unclear is whether or not this vscale_border method has utility in achieving anything vscale_mode=1 is unable to achieve.

**Comment by meauxdal** [comment]
It does seem like it can be used to reduce the total vertical multiplier in cases where the default vertical multiplier for a given core/resolution at vscale_mode=1 is too high for taste.

**Comment by meauxdal** [comment]
Alright... it is making more sense now. The vscale_border is a little bit more robust overall since it does allow you to reduce the vertical multipler. This is relevant in cases like SMS where you can't get 2048:1344 in video_mode=12 due to the horizontal width, so this gives you an additional option for more correct aspect ratio at the higher resolution where you'd normally be limited to square or overly skinny pixels.

**Comment by dfilskov** [comment]
Yes - it should also work for 5:4 screens and even 1:1 screens (perhaps only the one from Eizo) ... and even 3:4 screens (4:3 screens that rotate) and 4:5.

**Comment by dfilskov** [comment]
> * MiSTer's NES core only outputs 256x240 when in PAL/Dendy mode. In NTSC mode it will output 256x224.

I've tested - it doesn't change between PAL/Dendy and NTSC.

> * MiSTer's Genesis/MegaCD cores should be putting out the same resolutions in both NTSC and PAL modes - both television formats are capable of both 256 and 320 width modes, but in the MiSTer cores the visible lines should be the same in my experience.

I've tested - it seems to change. Please let me know if you find that it's wrong.

> * The relevant width for SMS is 256, not 248.

I've tested :) - please let me know if you find that I made a mistake. The resolution seems to change depending on the game that you load. I haven't tested if the resolutions are different if you set Region to Japan instead of US/EU, though.

Also please note that e.g. GAUNT2 video info says 336:240 but actually is 336:256.

**Comment by meauxdal** [comment]
I will do some additional testing regarding these things.

I should be more clear regarding NES. In my experience, NTSC games are generally 256x224 and PAL games are generally 256x240 - this is in terms of the visible picture, which seems to match the dimensions when taking a screenshot in most cores. I am sure there are exceptions. I should have been more clear that the game loaded seems to be the determining factor there, not the mode set on MiSTer. 

Edit: Well, I take that back, it looks like the mode itself is the thing switching the resolution, at least in RC Pro-Am (Europe). When loaded in NTSC mode, it loads as 256x224. When switched to PAL mode, the resolution becomes 256x240. I took screenshots of the USA version in NTSC and the Europe version in PAL below with the internal MiSTer screenshot tool.

![20210215_164504-R C  Pro-Am (USA) (Rev A)](https://user-images.githubusercontent.com/68095521/107996963-ad286e00-6faf-11eb-843f-d9984391ab11.png)
USA, NTSC, 256x224

![20210215_164450-R C  Pro-Am (Europe) (Rev A)](https://user-images.githubusercontent.com/68095521/107996964-af8ac800-6faf-11eb-9f7d-85c452608fab.png)
Europe, PAL, 256x240

Could you specify the NES/MD/SMS games you are testing in each scenario so I know what I am looking for? Thank you!

Another note related to your initial post, it seems my issues with the Minimig ratios may have been a user error on my end related to the "Adjust video position" function. After renaming a file related to the function, existing ratios I made earlier that I had been having issues with started working.

**Comment by meauxdal** [comment]
All SMS games I have tested thus far on the latest official build are 256 pixels wide, including during horizontal scrolling sections (and on various other screens, see the Castle of Illusion screenshot below) where the left 8 columns are masked. Are you using the latest build for SMS? Is your BG setting set to the default? Ratios are correct when calculated for 256. Could you tell me which software you are using which is 248 pixels wide?

![20210215_170737-Black Belt (USA, Europe, Brazil)](https://user-images.githubusercontent.com/68095521/107997565-0e9d0c80-6fb1-11eb-927c-ecbe6b3ae9e0.png)
![20210215_170805-Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (Rev 1)](https://user-images.githubusercontent.com/68095521/107997566-0f35a300-6fb1-11eb-852e-d2db3ee4a5b3.png)
![20210215_170816-Enduro Racer ~ Super Cross (USA, Europe, Brazil)](https://user-images.githubusercontent.com/68095521/107997567-0f35a300-6fb1-11eb-8837-bb7e33fca979.png)
![20210215_170835-Golvellius - Valley of Doom (USA, Europe, Brazil)](https://user-images.githubusercontent.com/68095521/107997568-0f35a300-6fb1-11eb-91cd-9c294de77e31.png)
![20210215_170851-Wonder Boy in Monster Land (USA, Europe)](https://user-images.githubusercontent.com/68095521/107997569-0f35a300-6fb1-11eb-9473-2c84fa762d19.png)
![20210215_170900-Wonder Boy in Monster Land (USA, Europe)](https://user-images.githubusercontent.com/68095521/107997570-0f35a300-6fb1-11eb-85c2-b1a3c7e42b60.png)

**Comment by meauxdal** [comment]
Setting PAL or NTSC does not appear to affect resolution on the Genesis core, and both television formats have 256 and 320 width modes.

![20210215_171035-James Pond 3 (USA, Europe)](https://user-images.githubusercontent.com/68095521/107997716-74899400-6fb1-11eb-863f-fa067c1044d9.png)
PAL, 320x224

![20210215_171058-James Pond 3 (USA, Europe)](https://user-images.githubusercontent.com/68095521/107997717-75222a80-6fb1-11eb-8ce4-7e09979dc072.png)
NTSC, 320x224

![20210215_171136-Addams Family, The (USA, Europe)](https://user-images.githubusercontent.com/68095521/107997718-75222a80-6fb1-11eb-9c86-82e4819e0cc8.png)
PAL, 256x224

![20210215_171203-Addams Family, The (USA, Europe)](https://user-images.githubusercontent.com/68095521/107997719-75222a80-6fb1-11eb-863a-d9a65a5805e8.png)
NTSC, 256x224

**Comment by dfilskov** [comment]
> I should be more clear regarding NES. In my experience, NTSC games are generally 256x224 and PAL games are generally 256x240 (...) When loaded in NTSC mode, it loads as 256x224

None of the few games I have loads in 256x224. Perhaps I'm just "unlucky" to have only PAL games. Or the video info is wrong - saying 240 when it's actually 224 in some of them?

Video of the games and their video-info:
https://www.dropbox.com/s/sn802o3qsgbppzn/2021-02-16%2021.44.39.mp4?dl=0

**Comment by meauxdal** [comment]
Here is the behavior I would expect to see on your end:
https://youtu.be/AW919XTiZ4o
Even with no game loaded, the NTSC/PAL/Dendy switch in the OSD affects internal resolution. I'm not sure what the issue is here. 
[MiSTer.zip](https://github.com/meauxdal/MiSTer_Custom_Aspect_Ratios/files/5992069/MiSTer.zip)
I've attached my 720p .ini file in case a setting differs which could explain this.

**Comment by dfilskov** [comment]
> All SMS games I have tested thus far on the latest official build are 256 pixels wide

I think you're right! - not sure how I ended up with a 248 setting - 256 seems to be correct. Spreadsheet adjusted accordingly.

**Comment by dfilskov** [comment]
> Here is the behavior I would expect to see on your end:
> https://youtu.be/AW919XTiZ4o
> Even with no game loaded, the NTSC/PAL/Dendy switch in the OSD affects internal resolution.

OK this is odd but I found the "bug": When you change to a custom ratio this core stays on the PAL resolution (not so if ratio is set to 'Original'). At least on my setup.

I guess I should report this is a an issue for this core - unless it's a general issue in the MiSTer framework.

Do you get this behaviour too?

**Comment by meauxdal** [comment]
The video I posted above was done with the Aspect Ratio set to 8:7 already, so I guess not. Tested again just now, same behavior as indicated in my video. That's quite odd, indeed.

**Comment by meauxdal** [comment]
Perhaps it is an issue with vscale_border and custom_aspect_ratio in tandem?

**Comment by dfilskov** [comment]
I've created an issue now:

https://github.com/MiSTer-devel/NES_MiSTer/issues/234

**Comment by dfilskov** [comment]
GENESIS

> both television formats have 256 and 320 width modes.

You're right. Do you have an idea what to call those two versions of the GENESIS section in the spreadsheet?

I don't see a good setting that would work for both resolutions on my setup but e.g. for 1920x1080 this could work (if the user switches ratio manually when loading a game):


[GENESIS]
vscale_border=92
custom_aspect_ratio_1=1280:896 ; 320 x 224
custom_aspect_ratio_2=1024:896 ; 256 x 224

**Comment by meauxdal** [comment]
In my repository I specify the base resolution in the comments first. The way I refer to these games are just as 320-width or 256-width games, or maybe even just 256/320. There are quite a few games, especially MegaCD games, which actually switch resolution in various scenes. Sonic CD switches back and forth repeatedly depending on scene.

There is one magic number I know of: at 1920x1080 resolution with vscale_mode=1, the 10:7 custom aspect ratio will achieve both 5x/4x hori/vert scaling in 256-width games and 4x/4x scaling in 320-width games.

**Comment by meauxdal** [comment]
I'm spitballing in this comment thread, not necessarily directly related to the original post at this point.

Will have to rethink the best application of this repository moving forward now that automatic H+V integer scaling is being added to the main repo. I think the custom ratios will still fit the bill for some users, especially in cases where you want a separate ratio than what you're given by the Wider and Narrower options, but it may be worth sorting things for their most likely use cases since the general idea will be much better covered by default options.

dfilskov, I appreciate your contributions and our discussions!

**Comment by dfilskov** [comment]
I was (happily) thinking the same thing :)
